[package]
name = "indiedevcasts-website"
version = "0.1.0"
authors = ["Julian Didier (theredfish) <did.julian@gmail.com>"]

[dependencies]
actix = "0.7"
actix-web = "0.7"
env_logger = "0.5"
serde_derive = "1.0.71"
serde = "1.0.71"
validator = "0.7.1"
validator_derive = "0.7.1"
